- name: Add CD/DVD device to an existing VM in vCenter
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/vm_vars.yml

  tasks:
    - name: Add CD/DVD device to the VM
      community.vmware.vmware_guest_cdrom:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        cluster: "{{ cluster_name }}"
        name: "{{ vm_name }}"
        cdrom:
          state: present
          type: "client_device"
      delegate_to: localhost
